linters-settings:
  goimports:
    local-prefixes: github.com/calyptia/go-s3-client
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  funlen:
    lines: 1000
    statements: 250

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - dupl
    - exportloopref
    - forcetypeassert
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - ifshort
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - funlen
issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - funlen
        - stylecheck
        - gocyclo
        - gocognit
        - revive
        - dupl
        - goconst
        - errcheck
        - bodyclose
        - gomnd
        - nolintlint
      path: ".*test.*.go"
